const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
import {gameData,stage,dataVersion} from './game-data.js';
import * as THREE from '../vendor/three.module.js';
import {loadCharacter} from './character.js';
import {TYPES} from './encounter.js';
export function createDebugViewer({gradient,getExpansion,getSnapshot,onClose}){
 const panel=document.createElement('section');panel.id='debug-viewer';panel.className='hidden';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','デバッグ画面');
 panel.innerHTML=`<header><h2>DEBUG / モーション・ステータス</h2><button id="debug-close">ゲームに戻る（Esc）</button></header><div class="debug-layout"><div><canvas id="debug-canvas" aria-label="モーションプレビュー"></canvas><p id="debug-status" role="status"></p><div class="debug-controls"><label>キャラクター <select id="debug-character"><option value="player">天使ちゃん</option><option value="imp">小悪魔</option><option value="captain">中悪魔</option><option value="boss">大悪魔</option></select></label><label>モーション <select id="debug-motion"></select></label><button id="debug-play">停止</button><label>再生速度 <select id="debug-speed"><option value=".25">0.25倍</option><option value=".5">0.5倍</option><option value="1" selected>1倍</option><option value="2">2倍</option></select></label><label>時間 <input id="debug-time" type="range" min="0" max="12" step=".01" value="0"><output id="debug-time-value">0.00秒</output></label><label>見る方向 <input id="debug-angle" type="range" min="-180" max="180" value="25"></label><label>距離 <input id="debug-zoom" type="range" min="7" max="24" value="12"></label></div></div><aside id="debug-stats"></aside></div>`;
 document.body.append(panel);const $=id=>panel.querySelector('#debug-'+id);
 const soundPanel=document.createElement('section');soundPanel.className='debug-sound';soundPanel.innerHTML=`<h3>サウンド確認</h3><div class="debug-controls"><label>効果音 <select id="debug-sfx" aria-label="確認する効果音"></select></label><button id="debug-sfx-play">効果音を再生</button><label>BGM <select id="debug-bgm" aria-label="確認するBGM"></select></label><button id="debug-bgm-play">BGMを再生</button><label>ボイス <select id="debug-voice" aria-label="確認するボイス"></select></label><button id="debug-voice-play">ボイスを再生</button><label><input id="debug-loop" type="checkbox">BGMループ</label><button id="debug-audio-stop">停止・先頭へ</button></div><p id="debug-audio-status" role="status">音源リストを読み込み中…</p><audio id="debug-audio" controls preload="none" aria-label="試聴プレイヤー"></audio><p>試聴音量はプレイヤー右端で調整できます。ゲームに戻ると試聴を停止します。BGM：びーみゅ／音楽ファイルの抜き出し・二次配布禁止。</p>`;panel.append(soundPanel);
 const preview=$('audio');preview.volume=.45;let soundManifest=null,previewKind=null;
 const stopAudio=()=>{preview.pause();preview.currentTime=0;};
 async function loadSounds(){try{const response=await fetch(new URL('../assets/audio/manifest.json',import.meta.url));if(!response.ok)throw Error('manifest');soundManifest=await response.json();for(const kind of ['sfx','bgm','voice']){const entries=Object.entries(soundManifest).filter(([,m])=>m.kind===kind);$(kind).replaceChildren(...entries.map(([key,m])=>{const option=document.createElement('option');option.value=key;option.textContent=m.label;return option;}));}$('audio-status').textContent='効果音・BGM・ボイスを選んで再生してください';}catch{$('audio-status').textContent='音源リストを取得できません。画面を開き直してください';}}
 async function audition(kind){if(!soundManifest)return;const key=$(kind).value,meta=soundManifest[key];if(!meta)return;stopAudio();previewKind=kind;preview.src=new URL('../assets/audio/'+(meta.file||key+'.wav'),import.meta.url).href;preview.loop=kind==='bgm'&&$('loop').checked;$('audio-status').textContent=meta.label;try{await preview.play();}catch{$('audio-status').textContent='再生できません。もう一度再生ボタンを押してください';}}
 $('voice-play').onclick=()=>audition('voice');$('sfx-play').onclick=()=>audition('sfx');$('bgm-play').onclick=()=>audition('bgm');$('audio-stop').onclick=stopAudio;$('loop').onchange=()=>preview.loop=previewKind==='bgm'&&$('loop').checked;
 document.addEventListener('visibilitychange',()=>{if(document.hidden)preview.pause();});
 let renderer,scene,camera,angel,enemy,current,active=false,playing=true,time=0,initializing,dirty=true;
 const motions={player:{idle:'浮遊',rise:'上昇・のけぞり',fall:'下降・飛び降り',turn:'ターン・体育座り',attack:'攻撃・羽ばたき'},enemy:{idle:'移動',guard:'ファイティング・チャージ',attack:'攻撃',damage:'被弾',death:'撃破・墜落',side:'横向き',inverted:'逆さま',aim:'上半身追従'}};
 function options(){const entries=motions[$('character').value==='player'?'player':'enemy'];$('motion').replaceChildren(...Object.entries(entries).filter(([v])=>!(['side','inverted'].includes(v)&&$('character').value!=='boss')&&!(v==='aim'&&$('character').value==='imp')).map(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;return o;}));time=0;}
 options();
 async function initialize(){if(initializing)return initializing;initializing=(async()=>{
  renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));scene=new THREE.Scene();scene.background=new THREE.Color('#171b2c');camera=new THREE.PerspectiveCamera(40,1,.1,150);
  scene.add(new THREE.HemisphereLight('#fff6de','#7875ad',3));const light=new THREE.DirectionalLight('#fff3d0',3);light.position.set(4,6,5);scene.add(light);scene.add(new THREE.GridHelper(16,16,0x7a938f,0x30394c));
  angel={body:new THREE.Group()};angel.g=new THREE.Group();angel.g.add(angel.body);scene.add(angel.g);angel.g.position.y=3;
  await loadCharacter(angel,gradient);$('status').textContent='モデル準備完了 / 戦闘時間は停止中';
 })().catch(e=>{$('status').textContent='モデル読み込み失敗：'+e.message;initializing=null;throw e;});return initializing;}
 function select(){if(!scene)return;dirty=true;time=0;if(enemy){scene.remove(enemy.g);enemy.g.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.dispose();});enemy=null;}
  current=$('character').value;angel.g.visible=current==='player';if(current!=='player'){const expansion=getExpansion();if(!expansion){$('status').textContent='敵モデルを読み込み中です。少し待ってキャラクターを選び直してください';return;}enemy={type:current,g:new THREE.Group(),phase:0,hp:TYPES[current].hp};scene.add(enemy.g);expansion.attachEnemy(enemy);enemy.g.scale.setScalar(4.8/TYPES[current].height);enemy.g.position.y=3;$('status').textContent='モデル準備完了 / 戦闘時間は停止中';}}
 $('character').onchange=()=>{options();select();};$('motion').onchange=()=>{time=0;dirty=true;};$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'停止':'再生';};$('time').oninput=()=>{time=Number($('time').value);dirty=true;playing=false;$('play').textContent='再生';};$('close').onclick=onClose;
 function stats(){const s=getSnapshot();$('stats').innerHTML=`<h3>プレイヤー</h3><dl><dt>体力</dt><dd>${s.hp} / ${gameData.player.maxHp}</dd><dt>通常弾 / 聖槍ダメージ</dt><dd>${gameData.weapons.gun.damage} / ${gameData.weapons.spear.damage}</dd><dt>納豆ミサイル</dt><dd>${gameData.weapons.natto.damage} × 最大${gameData.weapons.natto.capacity}発</dd><dt>通常速度 / 加速速度</dt><dd>${gameData.player.speed} / ${gameData.player.boostSpeed}</dd><dt>残り時間</dt><dd>${s.time.toFixed(1)} 秒</dd><dt>編隊 / 撃破数</dt><dd>${s.wave} / ${s.kills}</dd></dl><h3>敵の基本ステータス</h3><table><tr><th>敵</th><th>最大HP</th><th>身長</th><th>当たり判定半径</th></tr>${Object.values(TYPES).map(x=>`<tr><td>${escapeHtml(x.label)}</td><td>${x.hp}</td><td>${x.height}</td><td>${x.radius}</td></tr>`).join('')}</table><h3>出現中の敵</h3><table><tr><th>種類</th><th>現在HP</th><th>チャージ</th></tr>${s.enemies.filter(x=>x.hp>0).map(x=>`<tr><td>${escapeHtml(TYPES[x.type].label)}</td><td>${x.hp.toFixed(2)}</td><td>${Math.round((x.chargeRatio||0)*100)}%</td></tr>`).join('')}</table><p>プレビューは独立モデルです。戦闘中の姿勢・HPには影響しません。</p>`;}
 return {async open(){active=true;if(!soundManifest)loadSounds();panel.classList.remove('hidden');stats();$('close').focus();try{await initialize();if(active)select();}catch{}},close(){stopAudio();preview.removeAttribute('src');preview.load();active=false;panel.classList.add('hidden');},update(dt){if(!active||!renderer||!current)return;if(playing)time=(time+dt*Number($('speed').value))%12;$('time').value=time;$('time-value').textContent=time.toFixed(2)+'秒';const m=$('motion').value;
  if(playing||dirty){if(current==='player'){angel.body.rotation.set(0,0,0);if(m==='attack')angel.attack();angel.animate(time,52,playing?dt:1,m==='rise'?.65:m==='fall'?-.65:0,m==='turn'?{tuck:Math.sin(Math.PI*(time%2.4)/2.4)**2,open:0}:null);}
  else if(enemy){enemy.fighting=m==='guard'?1:0;enemy.charge=m==='guard'?1:0;enemy.attackAge=m==='attack'?(time%.8):2;enemy.damageAge=m==='damage'?(time%.55):2;enemy.deathAge=m==='death'?time%4:undefined;enemy.motionTime=m==='side'?7.5:m==='inverted'?4.5:time;getExpansion()?.animateEnemy(enemy,time,playing?dt:1,m==='aim'?new THREE.Vector3(Math.sin(time)*8,4,8):new THREE.Vector3(0,3,12));enemy.g.position.y=m==='death'?3-(time%4)*.65:3;}
  dirty=false;}
  const width=$('canvas').clientWidth,height=$('canvas').clientHeight;if(renderer.domElement.width!==Math.round(width*renderer.getPixelRatio())||renderer.domElement.height!==Math.round(height*renderer.getPixelRatio()))renderer.setSize(width,height,false);camera.aspect=width/Math.max(1,height);camera.updateProjectionMatrix();const angle=Number($('angle').value)*Math.PI/180,d=Number($('zoom').value);camera.position.set(Math.sin(angle)*d,5,Math.cos(angle)*d);camera.lookAt(0,3,0);renderer.render(scene,camera);
 }};
}
